package dev.opencode.android.core.testing

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import java.io.InputStream

/**
 * Loads test fixtures recorded from live OpenCode servers (src/main/resources/fixtures).
 */
object Fixtures {
    fun stream(path: String): InputStream {
        val normalized = if (path.startsWith("/")) path.substring(1) else path
        val resourcePath = if (normalized.startsWith("fixtures/")) normalized else "fixtures/$normalized"
        return Fixtures::class.java.classLoader?.getResourceAsStream(resourcePath)
            ?: error("Fixture not found: $resourcePath")
    }

    fun raw(path: String): String = stream(path).bufferedReader().use { it.readText() }

    fun json(path: String): JsonElement = Json.parseToJsonElement(raw(path))

    fun events(): List<String> =
        raw("events.jsonl").lines().filter { it.isNotBlank() }

    /**
     * One minimal envelope for every named event type, generated by `tools/gen-event-payloads.mjs`
     * from the vendored TypeScript declarations.
     *
     * The recorded [events] stream is real server output but it only exercises 47 of the 93 types,
     * so this is what covers the rest: a type with a registry entry and no payload here has a
     * binding that no test has ever decoded.
     */
    fun eventPayloads(): List<String> =
        raw("event-payloads.jsonl").lines().filter { it.isNotBlank() }

    val allScenarios = listOf(
        "text",
        "reasoning",
        "shell",
        "edit",
        "question",
        "subagent",
        "error",
        "long",
    )
}
